apiVersion: v1
kind: Service
metadata:
  name: mcp-tank-operator
  namespace: mcp-tank-operator
spec:
  type: ClusterIP
  selector:
    app: mcp-tank-operator
  ports:
    - name: http
      port: 80
      targetPort: proxy
